name: Update bc.png from BINGCHA_URL

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点抓取
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-bc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Download subscription and generate bc.png
        run: |
          mkdir -p an
          OUT="an/bc.png"
          SUB_URL="${{ secrets.BINGCHA_URL }}"

          python - <<'EOF'
import requests, os, re

sub_url = os.environ["SUB_URL"]
out_file = os.environ["OUT"]

try:
    r = requests.get(sub_url, timeout=30)
    r.raise_for_status()
    content = r.text

    # M3U 头部，保留大佬 EPG 引用
    lines = ['#EXTM3U x-tvg-url="https://fy.188766.xyz/all.xml.gz" catchup="append" catchup-source="?playbackbegin=${(b)yyyyMMddHHmmss}&playbackend=${(e)yyyyMMddHHmmss}"\n']

    # 匹配所有播放 URL，保持原顺序
    urls = re.findall(r'https?://[^\s]+', content)
    for url in urls:
        # 自动提取频道 ID
        match = re.search(r'id=([A-Za-z0-9_]+)', url)
        channel_name = match.group(1) if match else "Channel"
        logo = f"https://fy.188766.xyz/logo/fanmingming/live/tv/{channel_name}.png"
        group_title = "大佬频道"
        lines.append(f'#EXTINF:-1 tvg-id="{channel_name}" tvg-name="{channel_name}" tvg-logo="{logo}" group-title="{group_title}",{channel_name}\n')
        lines.append(url + "\n")

    with open(out_file, "w", encoding="utf-8") as f:
        f.writelines(lines)

    print(f"{out_file} generated successfully!")

except Exception as e:
    print(f"Failed to fetch subscription. Error: {e}")
EOF

      - name: Commit & push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add an/bc.png || true
          git commit -m "Update bc.png from BINGCHA_URL" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUB_URL: ${{ secrets.BINGCHA_URL }}
          OUT: an/bc.png
