name: Update bc file

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 UTC 0 点
  workflow_dispatch:       # 手动触发

permissions:
  contents: write

jobs:
  update-bc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create directory
        run: mkdir -p an

      - name: Download bc.png from BINGCHA_URL via gh-proxy
        run: |
          curl -L "https://gh-proxy.com/${{ secrets.BINGCHA_URL }}" -o an/bc.png

      - name: Commit and push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add an/bc.png
          git commit -m "Update bc.png from BINGCHA_URL" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
