name: 更新 BINGCHA 文件

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-bc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download BINGCHA subscription via Proxy
        run: |
          mkdir -p an
          # 通过代理下载订阅源
          curl -L "${{ secrets.BINGCHA_URL }}" -o an/bc.m3u

      - name: Optional: Display first few lines
        run: head -n 10 an/bc.m3u

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add an/bc.m3u
          git commit -m "更新 bc 文件" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
