name: Update BC File

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-bc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download BC Subscription via Proxy
        run: |
          mkdir -p an
          # Download subscription file through proxy
          curl -L "${{ secrets.BINGCHA_URL }}" -o an/bc.m3u

      - name: Preview Downloaded File
        run: head -n 10 an/bc.m3u

      - name: Commit and Push if Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add an/bc.m3u
          git commit -m "Update bc.m3u file" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
