name: Update bc.m3u via Proxy

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 UTC 0 点
  workflow_dispatch:       # 允许手动触发

permissions:
  contents: write

jobs:
  update-bc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ensure folder exists
        run: mkdir -p an

      - name: Download and extract bc.m3u via proxy
        run: |
          echo "Downloading from proxy..."
          curl -L "https://gh-proxy.com/${{ secrets.BINGCHA_URL }}" -o tmp.gz
          
          if file tmp.gz | grep -q gzip; then
            gunzip -c tmp.gz > an/bc.m3u
            echo "Download and extract succeeded"
          else
            echo "Download failed or not a gzip file"
            exit 1
          fi

      - name: Commit and push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add an/bc.m3u
          git commit -m "Update bc.m3u via proxy" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
