name: Update bc.png from subscription (auto, secret URL)

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 UTC 00:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Download subscription and generate full M3U bc.png
        run: |
          mkdir -p an
          OUT="an/bc.png"
          SUB_URL="${{ secrets.BINGCHA_URL }}"  # 使用你的 secret 名称

          echo "Fetching subscription content and generating M3U ..."
          python - << 'EOF'
import requests
import re
import os

sub_url = os.environ["SUB_URL"]
out_file = os.environ["OUT"]

try:
    r = requests.get(sub_url, timeout=30)
    r.raise_for_status()
    data = r.text

    m3u_lines = ['#EXTM3U x-tvg-url="https://fy.188766.xyz/all.xml.gz" catchup="append" catchup-source="?playbackbegin=${(b)yyyyMMddHHmmss}&playbackend=${(e)yyyyMMddHHmmss}"\n']

    # 匹配 URL 和频道名
    pattern = re.compile(r'(https?://[^\s]+)')
    urls = pattern.findall(data)

    for url in urls:
        match = re.search(r'id=([A-Za-z0-9_]+)', url)
        channel_name = match.group(1) if match else "Channel"
        logo_url = f"https://fy.188766.xyz/logo/fanmingming/live/tv/{channel_name}.png"
        group_title = "大佬频道"

        m3u_lines.append(f'#EXTINF:-1 tvg-id="{channel_name}" tvg-name="{channel_name}" tvg-logo="{logo_url}" group-title="{group_title}",{channel_name}\n')
        m3u_lines.append(url + "\n")

    with open(out_file, "w", encoding="utf-8") as f:
        f.writelines(m3u_lines)

    print(f"{out_file} generated successfully!")

except Exception as e:
    print(f"Failed to fetch or generate bc.png: {e}")
EOF

      - name: Commit & push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add an/bc.png || true
          git commit -m "Update bc.png from subscription link (secret URL)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUB_URL: ${{ secrets.BINGCHA_URL }}
          OUT: an/bc.png
