name: Fetch IPTV Source (bc.png)

on:
  schedule:
    - cron: '0 0 * * *'    # 每天 UTC 0 点运行
  workflow_dispatch:        # 支持手动触发

permissions:
  contents: write

jobs:
  fetch-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create folder
        run: mkdir -p an

      - name: Download IPTV source
        run: |
          curl -L "${{ secrets.BINGCHA_URL }}" -o an/bc.png

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add an/bc.png
          git commit -m "Auto update bc.png from remote source" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
