name: Update bc.m3u via Proxy

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 UTC 0 点
  workflow_dispatch:       # 允许手动触发

permissions:
  contents: write

jobs:
  update-bc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure directory exists
        run: mkdir -p an

      - name: Download and extract bc.m3u via proxy
        run: |
          curl -L "https://gh-proxy.com/${{ secrets.BINGCHA_URL }}" | gunzip > an/bc.m3u

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add an/bc.m3u
          git commit -m "Update bc.m3u from remote source via proxy" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
