name: Update bc file

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 UTC 0 点抓取
  workflow_dispatch:       # 手动触发

permissions:
  contents: write

jobs:
  update-bc:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout 仓库
      - uses: actions/checkout@v3

      # Step 2: 下载大佬源（通过 ghproxy 代理，使用 secret）
      - name: Download bc.png via ghproxy
        run: |
          mkdir -p an
          curl -L "https://ghproxy.com/${{ secrets.BINGCHA_URL }}" -o an/bc.png

      # Step 3: 提交并推送更改
      - name: Commit and push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add an/bc.png
          git commit -m "Update bc.png via ghproxy" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
