name: Update ds.png

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 UTC 0 点
  workflow_dispatch:       # 允许手动触发

permissions:
  contents: write

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show file status
        run: |
          echo "Current status of an/ds.png:"
          git status an/ds.png

      - name: Commit and push safely
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add an/ds.png
          
          # 如果文件没变化，直接打印提示，不报错
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            # 尝试提交并 push，失败也不会让 workflow fail
            git commit -m "Update ds.png" || echo "Commit failed, probably no changes"
            git push || echo "Push failed, maybe no permission or conflict"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
